### ISSUE TITLE
Display: none; possibly breaking layout

### ISSUE THREAD

**Issue by devonmather** [jonathantneal/flexibility#31] opened 2016-02-03 19:54 UTC
Hey,

Introducing display:none; on an element within a flex container in IE 8/9 seems to break the layout, I've modified a codepen given by @edge0703 earlier (see demo below).

However I apoligize if I'm being mislead by browserstack, which is what I'm using as emulation since Edge and IE 11 give completely opposing results.

Demo here: 
http://devoncmather.com/flex-test.html

Screen shots here:
https://dev.windows.com/en-us/microsoft-edge/tools/screenshots/#http://devoncmather.com/flex-test.html

Thanks in advance,
Devon Mather

**Comment by edge0703** [comment] 2016-02-04 06:44
Really, I can see no difference between Chrome, IE11 and Edge. What is supposed to happen and what really happens?

**Comment by devonmather** [comment] 2016-02-04 09:33
Hey @edge0703 your screen shot looks correct, however in IE8 browserstack I get the following.

https://www.browserstack.com/screenshots/7c7a1304e6525ce622a918ecb00616edc3840b6a/win7_ie_10.0.png

**Comment by edge0703** [comment] 2016-02-04 12:06
Oh, you talked about IE8. You didn't mention that in your initial post, I thought it was all about IE11 and Edge. But I can conform it, in IE8, 9 and 10 the display isn't correct (rows instead of cols).

**Comment by devonmather** [comment] 2016-02-04 12:22
Ok, updated initial comment to reference IE 8 and 9. You have confirmed that the bug exists for you as well?

**Comment by edge0703** [comment] 2016-02-04 12:37
Yes, I can confirm that: http://s.codepen.io/edge0703/debug/XXPqjm

The moment you have an element that has "display: none" it breaks in IE8 - IE10. Also if you put it into the CSS and not inline.

**Comment by jonathantneal** [comment] 2016-06-29 14:24
This was due to how `currentStyle` was checked which is now resolved in v2

**Closed by jonathantneal** 2016-06-29 14:24 UTC
